name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/dev-docker-publish.yml@th2-4135-trivy-workflow
    with:
      docker-username: ${{ github.repository_owner }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  trivy-scan-job:
    uses: th2-net/.github/.github/workflows/trivy-scan.yml@th2-4135-trivy-workflow
    needs: [build-job]
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.build-job.outputs.version }}


